### PR TITLE
fix for other_fuels being nil

### LINKED ISSUE #27: reporting measure fails when there are no additional fuels in the model
when additional_fuels/other_fuels are nil, measure crashes.

### LINKED ISSUE #29: restore default_feature_report function for backward compatibility

### PR DESCRIPTION
**Pull request by kflemin**

### CODE REVIEW

File: lib/measures/default_feature_reports/measure.rb [hunk 1]
```diff
@@ -608,8 +608,12 @@ def run(runner, user_arguments)
     feature_report.reporting_periods[0].fuel_oil_kwh = convert_units(fuel_oil, 'GJ', 'kWh') unless fuel_oil.nil?
 
     # other_fuels
+    runner.registerWarning("PROPANE KWH: #{feature_report.reporting_periods[0].propane_kwh}")
+    runner.registerWarning("FUEL OIL KWH: #{feature_report.reporting_periods[0].fuel_oil_kwh}")
```
Comment (joseph-robertson) [inline lib/measures/default_feature_reports/measure.rb:612]: Are these debug statements?

Comment (kflemin) [reply lib/measures/default_feature_reports/measure.rb]: yes, i just removed them. thanks!
